name: homelab

services:
  homelab:
    build: .
    container_name: homelab
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    security_opt:
      - no-new-privileges:true
    cap_add:
      - NET_RAW
    read_only: false
    tmpfs:
      - /tmp
  guacd:
    image: guacamole/guacd:latest
    container_name: guacd
    restart: unless-stopped
